// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtr8cF_5qW2Xw40z59NccRAtu4MkKdbxk',
    appId: '1:815884487412:web:df5478c542503f695b6ca1',
    messagingSenderId: '815884487412',
    projectId: 'aprendendo-com-as-maos',
    authDomain: 'aprendendo-com-as-maos.firebaseapp.com',
    storageBucket: 'aprendendo-com-as-maos.appspot.com',
    measurementId: 'G-4P2PB6SFTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEezozp3zIYF2WIJr60YImyHBbl_XnVAk',
    appId: '1:815884487412:android:c579377ada57ed555b6ca1',
    messagingSenderId: '815884487412',
    projectId: 'aprendendo-com-as-maos',
    storageBucket: 'aprendendo-com-as-maos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7tPEdg70MPQ7MEABgvHYCHEiW8ce-1-Q',
    appId: '1:815884487412:ios:1cd733a19ebbdc895b6ca1',
    messagingSenderId: '815884487412',
    projectId: 'aprendendo-com-as-maos',
    storageBucket: 'aprendendo-com-as-maos.appspot.com',
    iosBundleId: 'com.example.aprendendoComAsMaos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7tPEdg70MPQ7MEABgvHYCHEiW8ce-1-Q',
    appId: '1:815884487412:ios:37a6caaf4061fc395b6ca1',
    messagingSenderId: '815884487412',
    projectId: 'aprendendo-com-as-maos',
    storageBucket: 'aprendendo-com-as-maos.appspot.com',
    iosBundleId: 'com.example.aprendendoComAsMaos.RunnerTests',
  );
}
